#!/usr/bin/env bash
#
# install.sh — set up (or update) Sparrow-WiFi on this device.
#
# Creates a dedicated Python venv for the app, installs system + Python
# dependencies, and registers a menu launcher that elevates to root at
# click time (the WiFi scanning back end needs root).
#
# Usage:
#   ./install.sh            # first-time install / re-run to repair
#   ./install.sh --update   # git pull, then refresh venv + launcher
#
# Design notes:
#   * aarch64 (this device) has no reliable PyQt5/PyQtChart/QScintilla
#     wheels, so those come from apt (arm64 .debs) and the venv is created
#     with --system-site-packages to reuse them. Only small pure-Python
#     deps are pip-installed into the venv.
#   * The interactive shell here has a `~/.pygpsclient` venv shadowing
#     python3 on PATH, so we build the venv with an explicit /usr/bin/python3.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/venv"
SYS_PY="/usr/bin/python3"
APP="$REPO_DIR/sparrow-wifi.py"

BIN_DST="/usr/local/bin/sparrow-wifi"
DESKTOP_DST="/usr/share/applications/sparrow-wifi.desktop"
ICON_DST="/usr/share/pixmaps/sparrow-wifi.png"

UPDATE=0
for arg in "$@"; do
    case "$arg" in
        --update) UPDATE=1 ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//' | head -20
            exit 0 ;;
        *) echo "Unknown option: $arg" >&2; exit 2 ;;
    esac
done

log()  { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }

if [[ $EUID -eq 0 ]]; then
    warn "Run this as your normal user (not root); it will call sudo when needed."
    exit 1
fi

# ---------------------------------------------------------------------------
# 0. Optional: pull the latest code before updating deps.
# ---------------------------------------------------------------------------
if [[ $UPDATE -eq 1 ]]; then
    log "Updating source (git pull)..."
    git -C "$REPO_DIR" pull --ff-only || warn "git pull failed; continuing with current checkout."
fi

# ---------------------------------------------------------------------------
# 1. System packages (arm64 Qt bindings + tools that shouldn't be pip-built).
# ---------------------------------------------------------------------------
APT_PKGS=(
    python3-pyqt5 python3-pyqt5.qtchart python3-pyqt5.qsci
    gpsd gpsd-clients
    python3-tk python3-setuptools python3-venv python3-pip
    python3-numpy python3-matplotlib python3-requests python3-dateutil
    pkexec
)
log "Installing system packages via apt (sudo)..."
sudo apt-get update
sudo apt-get install -y "${APT_PKGS[@]}"

# ---------------------------------------------------------------------------
# 2. Dedicated venv (reuses system Qt via --system-site-packages).
# ---------------------------------------------------------------------------
if [[ ! -x "$VENV_DIR/bin/python3" ]]; then
    log "Creating venv at $VENV_DIR ..."
    "$SYS_PY" -m venv --system-site-packages "$VENV_DIR"
else
    log "Reusing existing venv at $VENV_DIR"
fi

log "Installing/upgrading Python deps into the venv..."
"$VENV_DIR/bin/python3" -m pip install --upgrade pip
# QScintilla and PyQtChart come from apt (see note above), so they are
# intentionally excluded here. numpy/matplotlib/requests/dateutil are also
# satisfied by apt but pip is happy to leave them alone.
"$VENV_DIR/bin/python3" -m pip install --upgrade gps3 dronekit manuf

# ---------------------------------------------------------------------------
# 3. Sanity check: can the venv import the GUI stack?
# ---------------------------------------------------------------------------
log "Verifying imports..."
if "$VENV_DIR/bin/python3" - <<'PYEOF'
import sys
mods = ["PyQt5.QtWidgets", "PyQt5.QtChart", "PyQt5.Qsci", "manuf", "gps3"]
bad = []
for m in mods:
    try:
        __import__(m)
    except Exception as e:  # noqa: BLE001
        bad.append(f"{m}: {e}")
if bad:
    print("MISSING:", *bad, sep="\n  ")
    sys.exit(1)
print("All core imports OK")
PYEOF
then
    log "Import check passed."
else
    warn "Some imports failed — the app may not launch. See messages above."
fi

# ---------------------------------------------------------------------------
# 4. Menu launcher (elevates to root via pkexec, preserving the GUI session).
# ---------------------------------------------------------------------------
log "Installing launcher at $BIN_DST (sudo)..."
sudo tee "$BIN_DST" >/dev/null <<LAUNCHEOF
#!/usr/bin/env bash
# Sparrow-WiFi launcher — generated by install.sh. Runs the app from its
# dedicated venv, elevating to root (the scanner needs it) while keeping the
# graphical session reachable.
set -euo pipefail

VENV_PY="$VENV_DIR/bin/python3"
APP="$APP"

# Already root: just run.
if [[ \$EUID -eq 0 ]]; then
    exec "\$VENV_PY" "\$APP" "\$@"
fi

# X11 (incl. XWayland): let root talk to the display.
if [[ -n "\${DISPLAY:-}" ]]; then
    xhost +si:localuser:root >/dev/null 2>&1 || true
fi

# Detect the system light/dark scheme now, while still running as the invoking
# user — the elevated (root) process usually can't reach the user session bus,
# so we hand the result to the app via SPARROW_SYSTEM_THEME. XDG portal first
# (color-scheme: 1=dark, 2=light), then gsettings as a fallback.
SPARROW_SYSTEM_THEME="light"
_portal=\$(gdbus call --session --dest org.freedesktop.portal.Desktop \\
    --object-path /org/freedesktop/portal/desktop \\
    --method org.freedesktop.portal.Settings.Read \\
    org.freedesktop.appearance color-scheme 2>/dev/null || true)
case "\$_portal" in
    *"uint32 1"*) SPARROW_SYSTEM_THEME="dark" ;;
    *"uint32 2"*) SPARROW_SYSTEM_THEME="light" ;;
    *)
        _gs=\$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null || true)
        case "\$_gs" in *dark*) SPARROW_SYSTEM_THEME="dark" ;; esac
        ;;
esac
export SPARROW_SYSTEM_THEME

exec pkexec env \\
    DISPLAY="\${DISPLAY:-}" \\
    WAYLAND_DISPLAY="\${WAYLAND_DISPLAY:-}" \\
    XAUTHORITY="\${XAUTHORITY:-\$HOME/.Xauthority}" \\
    XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-}" \\
    QT_QPA_PLATFORM="\${QT_QPA_PLATFORM:-}" \\
    SPARROW_SYSTEM_THEME="\$SPARROW_SYSTEM_THEME" \\
    "\$VENV_PY" "\$APP" "\$@"
LAUNCHEOF
sudo chmod 755 "$BIN_DST"

# ---------------------------------------------------------------------------
# 5. Icon + .desktop menu entry.
# ---------------------------------------------------------------------------
log "Installing icon + desktop entry (sudo)..."
sudo install -m644 "$REPO_DIR/wifi_icon.png" "$ICON_DST"
sudo tee "$DESKTOP_DST" >/dev/null <<DESKTOPEOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Sparrow-WiFi
GenericName=WiFi / Bluetooth Spectral Awareness
Comment=2.4/5 GHz WiFi and Bluetooth scanning, spectrum analysis, GPS wardriving
Exec=$BIN_DST
Icon=sparrow-wifi
Terminal=false
Categories=Network;System;Security;
Keywords=wifi;wireless;scan;bluetooth;spectrum;gps;wardriving;
DESKTOPEOF
sudo chmod 644 "$DESKTOP_DST"
sudo update-desktop-database /usr/share/applications >/dev/null 2>&1 || true

log "Done."
echo
echo "  Launch from your application menu (\"Sparrow-WiFi\") or run: sparrow-wifi"
echo "  Update later with: $REPO_DIR/install.sh --update"
